# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 2, 21, 6, 12, 767340, tzinfo=utc), verbose_name='date started'),
        ),
    ]
