# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0002_auto_20160802_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparingWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=255)),
                ('position', models.IntegerField(unique=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.Analyzer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='unset', max_length=30)),
                ('state', models.CharField(default='unset', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='mean_radius_ready',
        ),
        migrations.RemoveField(
            model_name='task',
            name='profiling_ready',
        ),
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(default='unset', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default='unset', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 5, 9, 48, 53, 523022, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.AddField(
            model_name='result',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.Project'),
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.Task'),
        ),
        migrations.AddField(
            model_name='comparingwidget',
            name='tasks',
            field=models.ManyToManyField(to='gas_dynamics.Task'),
        ),
    ]
