# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gas_dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0002_auto_20160713_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
        migrations.AddField(
            model_name='profilingdatapart',
            name='rotor_blade_windage',
            field=gas_dynamics.models.ListField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilingdatapart',
            name='stator_blade_windage',
            field=gas_dynamics.models.ListField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 22, 49, 40, 205685, tzinfo=utc), verbose_name='date started'),
        ),
    ]
