# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:19
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0002_auto_20160708_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanum and underscore allowed')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 8, 13, 19, 48, 840032, tzinfo=utc), verbose_name='date started'),
        ),
    ]
