# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0003_auto_20160708_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeanRadiusSingleCompressorTask',
            new_name='SingleCompressorTask',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 10, 16, 5, 26, 248660, tzinfo=utc), verbose_name='date started'),
        ),
    ]
