# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0003_auto_20160730_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='profiling_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 30, 15, 47, 53, 514595, tzinfo=utc), verbose_name='date started'),
        ),
    ]
