# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0004_auto_20160710_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 10, 16, 51, 36, 789377, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='H_t_rel_first',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='H_t_rel_last',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='H_t_rel_max',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='H_t_rel_max_coord',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='c_a_rel_first',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='c_a_rel_last',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='constant_diameter_parameters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='d_rel_1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='eta_ad_first',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='eta_ad_last',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='eta_ad_max',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='eta_ad_max_coord',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='inlet_alpha',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='reactivity_first',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='reactivity_last',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='u_out_1',
            field=models.FloatField(blank=True),
        ),
    ]
