# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0007_auto_20160710_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 10, 17, 33, 33, 477179, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='constant_diameter_parameters',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='inlet_alpha',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
