# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0008_auto_20160710_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 10, 17, 39, 17, 343130, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.AlterUniqueTogether(
            name='singlecompressortask',
            unique_together=set([('project', 'name')]),
        ),
    ]
