# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 21:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0009_auto_20160710_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 10, 21, 14, 56, 21369, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='T_stag_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='mass_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='min_eta_ad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='p_stag_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='precision',
            field=models.FloatField(blank=True, default=0.03, null=True),
        ),
        migrations.AlterField(
            model_name='singlecompressortask',
            name='stage_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('user', 'name')]),
        ),
    ]
