# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0010_auto_20160710_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDataPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('mass_rate', models.FloatField()),
                ('T_stag_1', models.FloatField()),
                ('p_stag_1', models.FloatField()),
                ('min_eta_ad', models.FloatField()),
                ('stage_number', models.IntegerField()),
                ('precision', models.FloatField(default=0.03)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeanRadiusDataPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('u_out_1', models.FloatField()),
                ('d_rel_1', models.FloatField()),
                ('H_t_rel_first', models.FloatField()),
                ('H_t_rel_last', models.FloatField()),
                ('H_t_rel_max', models.FloatField()),
                ('H_t_rel_max_coord', models.FloatField()),
                ('eta_ad_first', models.FloatField()),
                ('eta_ad_last', models.FloatField()),
                ('eta_ad_max', models.FloatField()),
                ('eta_ad_max_coord', models.FloatField()),
                ('c_a_rel_first', models.FloatField()),
                ('c_a_rel_last', models.FloatField()),
                ('reactivity_first', models.FloatField()),
                ('reactivity_last', models.FloatField()),
                ('inlet_alpha', models.FloatField(blank=True, null=True)),
                ('constant_diameter_parameters', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 11, 15, 9, 497604, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.Project'),
        ),
        migrations.AddField(
            model_name='meanradiusdatapart',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.Task'),
        ),
        migrations.AddField(
            model_name='maindatapart',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('project', 'name')]),
        ),
    ]
