# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0011_auto_20160711_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BladeProfilePlot',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RenameField(
            model_name='maindatapart',
            old_name='index',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='meanradiusdatapart',
            old_name='index',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='H_t_rel_first',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='H_t_rel_last',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='H_t_rel_max',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='H_t_rel_max_coord',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='T_stag_1',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='c_a_rel_first',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='c_a_rel_last',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='constant_diameter_parameters',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='d_rel_1',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='eta_ad_first',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='eta_ad_last',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='eta_ad_max',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='eta_ad_max_coord',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='inlet_alpha',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='mass_rate',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='min_eta_ad',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='p_stag_1',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='reactivity_first',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='reactivity_last',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='stage_number',
        ),
        migrations.RemoveField(
            model_name='singlecompressortask',
            name='u_out_1',
        ),
        migrations.AlterField(
            model_name='maindatapart',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.SingleCompressorTask'),
        ),
        migrations.AlterField(
            model_name='meanradiusdatapart',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.SingleCompressorTask'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 16, 30, 16, 544153, tzinfo=utc), verbose_name='date started'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
