# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gas_dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0012_auto_20160728_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meanradiusdatapart',
            name='inlet_alpha',
            field=gas_dynamics.models.ListField(blank=True, default=[90]),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 14, 40, 32, 504702, tzinfo=utc), verbose_name='date started'),
        ),
    ]
