# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0012_auto_20160711_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingDataPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('rotor_velocity_law', models.CharField(max_length=1000)),
                ('stator_velocity_law', models.CharField(max_length=1000)),
                ('rotor_blade_profile', models.CharField(max_length=1000)),
                ('stator_blade_profile', models.CharField(max_length=1000)),
                ('rotor_blade_elongation', models.CharField(max_length=1000)),
                ('stator_blade_elongation', models.CharField(max_length=1000)),
                ('rotor_lattice_density', models.CharField(max_length=1000)),
                ('stator_lattice_density', models.CharField(max_length=1000)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas_dynamics.SingleCompressorTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='maindatapart',
            old_name='min_eta_ad',
            new_name='eta_ad_min',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 11, 19, 53, 5, 467214, tzinfo=utc), verbose_name='date started'),
        ),
    ]
