# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0013_auto_20160711_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meanradiusdatapart',
            old_name='constant_diameter_parameters',
            new_name='flow_section_type',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 12, 38, 17, 188384, tzinfo=utc), verbose_name='date started'),
        ),
    ]
