# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0014_auto_20160712_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindatapart',
            name='stage_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 12, 20, 58, 41, 479083, tzinfo=utc), verbose_name='date started'),
        ),
    ]
