# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gas_dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0015_auto_20160712_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', gas_dynamics.models.ListTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 16, 2, 25, 937245, tzinfo=utc), verbose_name='date started'),
        ),
    ]
