# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gas_dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0017_auto_20160713_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListModel',
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='rotor_blade_elongation',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='rotor_blade_profile',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='rotor_lattice_density',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='rotor_velocity_law',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='stator_blade_elongation',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='stator_blade_profile',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='stator_lattice_density',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='profilingdatapart',
            name='stator_velocity_law',
            field=gas_dynamics.models.ListField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 16, 28, 37, 66584, tzinfo=utc), verbose_name='date started'),
        ),
    ]
