# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gas_dynamics.models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_dynamics', '0018_auto_20160713_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meanradiusdatapart',
            name='flow_section_type',
            field=gas_dynamics.models.ListTextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 16, 41, 54, 239250, tzinfo=utc), verbose_name='date started'),
        ),
    ]
